### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by Vitallek** [rommmmmka/flowers-site#1]

**Comment by rommmmmka** [comment]
fuck you too nigger

**Comment by Vitallek** [comment]
no fuck you

**Comment by rommmmmka** [comment]
> no fuck you

why you white me this shit nigger bitch you enjoy my site??? y some words stop saying whou you fuck ith nigger idk bitch shut up !!!!!!!!!!! bitch my site best enjoy my code fucking slut

**Comment by Vitallek** [comment]
why you write me this shit nigger bitch you enjoy my site??? say some words stop saying whou u fuck bitch nigger idk bitch shut up !!!!!!!!!!! bitch my site best enjoy my code fucking slut ????

**Comment by rommmmmka** [comment]
@Vitallek is gay

**Comment by Vitallek** [comment]
@rommmmmka is lesbian

**Comment by rommmmmka** [comment]
ohohoh yes i like woman pussy

> @rommmmmka is lesbian
